version: '3.9'

services:
  backend:
    image: myorg/myapp:latest
    ports:
      - "8082:8080"
    environment:
      DB_URL: jdbc:mysql://database/chatdb
      DB_USER: root
      DB_PASSWORD: password
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      FLYWAY_ENABLED: true
    links:
      - "mysql:database"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatdb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: password
    restart: always

  mysqltest:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatdb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: password
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=sampleuser
      - POSTGRES_DB=sampledb
volumes:
  db-store:
networks:
  backendnet:
    driver: bridge